version: "3"
services:
  thumbor:
      image: apsl/thumbor:latest
      environment:
        - LOADER=thumbor.loaders.file_loader
        - FILE_LOADER_ROOT_PATH=/data
      ports:
        - "8000:8000"
      volumes:
        - ./data:/data
